version: "3"
services: 
  db:
    image: mysql
    ports:
      - "3306"
    volumes:
      - /dstack/apm/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /dstack/apm/apm_bi.sql:/docker-entrypoint-initdb.d/apm_bi.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
  web__8080:
    image: apm
    links:
      - "db:database"
    ports:
      - "8088:8080"
    depends_on:
      - db
    environment:
      - "DB_HOST=db"
      - "DB_PWD=root"
